name: End-to-end tests
on: 
    push:
        branches:
            - cypress_api_test
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: yarn cypress run
        uses: cypress-io/github-action@v6.1.0
        with:
          browser: true